const vehicle = {
    FRONTSIDE : ""
}

/*const vehicle2 = {
    originalData: {
      vin: '3MW5R1J51K8B02473',
      model: '330i',
      bodytype: 'G20',
      driveTrain: 'CONV',
      fuelType: 'PETROL',
      color: 'ALPINE WHITE 3',
      colorCode: '300',
      brand: 'BMW',
      yearOfConstruction: 2019,
      statisticsCommunityEnabled: false,
      statisticsAvailable: false,
      hub: 'HUB_US',
      hasAlarmSystem: true,
      dealer: {
        name: 'Leith BMW Rolls-Royce Motor Cars Raleigh',
        street: '5601 Capitol Blvd',
        postalCode: '27616',
        city: 'Raleigh',
        country: 'US',
        phone: '+1 919 8765432'
      },
      breakdownNumber: '+4989358957103',
      countryCode: 'V2-US',
      steering: 'LH',
      vehicleFinderRestriction: 'NONE',
      hmiVersion: 'id7',
      a4a: 'NOT_SUPPORTED',
      vehicleFinder: 'ACTIVATED',
      remote360: 'NOT_SUPPORTED',
      hornBlow: 'ACTIVATED',
      lightFlash: 'ACTIVATED',
      doorLock: 'ACTIVATED',
      doorUnlock: 'ACTIVATED',
      climateControl: 'NOT_SUPPORTED',
      climateNow: 'NOT_SUPPORTED',
      climateNowRES: 'ACTIVATED',
      climateControlRES: 'DEPARTURE_TIMER',
      chargingControl: 'NOT_SUPPORTED',
      chargeNow: 'NOT_SUPPORTED',
      sendPoi: 'ACTIVATED',
      rangeMap: 'NOT_SUPPORTED',
      lastDestinations: 'NOT_SUPPORTED',
      intermodalRouting: 'NOT_AVAILABLE',
      climateFunction: 'ENGINE_START',
      onlineSearchMode: 'MAP',
      smartSolution: 'NOT_SUPPORTED',
      carCloud: 'NOT_SUPPORTED',
      lscType: 'LSC_BASIS',
      ipa: 'NOT_SUPPORTED',
      puStep: '1119',
      exFactoryPUStep: null,
      remoteSoftwareUpgrade: 'ACTIVATED'
    },
    BMWURLs: BMWURLs { region: 'us', host: 'b2vapi.bmwgroup.us' },
    API: API {
      initialized: true,
      VEHICLE_VIEWS: {
        FRONTSIDE: 'FRONTSIDE',
        FRONT: 'FRONT',
        REARSIDE: 'REARSIDE',
        REAR: 'REAR',
        SIDE: 'SIDE',
        DASHBOARD: 'DASHBOARD',
        DRIVERDOOR: 'DRIVERDOOR',
        REARBIRDSEYE: 'REARBIRDSEYE'
      },
      region: 'us',
      username: 'aliafzal9323@gmail.com',
      password: '#Iamthesuper1',
      vehicles: [ [Circular] ],
      BMWURLs: BMWURLs { region: 'us', host: 'b2vapi.bmwgroup.us' },
      oauthToken: 'WHQVcrQzAfsQ18fwOLIBk5uA6pLMjZiv',
      refreshToken: 'jfvg6SsAFWaDvGnY1BbGthZTPdDjfvh94z1u27y8IRtwLGaF',
      tokenExpiresAt: Moment<2020-06-29T02:41:32-04:00>
    },
    images: {},
    status: null
  }*/